### PR TITLE
Use https for IPFS nodes

### PR DESCRIPTION
**Pull request by 2color**

### CODE REVIEW

**Review by izqui — APPROVED** [review]
We should use this opportunity to add Aragon's which is the one the client uses by default: https://ipfs.eth.aragon.network/ipfs

**Comment by kernelwhisperer** [comment]
There's a tricky part here. If you query a hash that is a directory, you only propagate the DAG of this hash, not the "children" files.

For example if you query the artifact of the agent app: `QmT2c6ffZ5e9vbQiQdWyRjZAxY9cMmZYNBEDW4Ne4dm2RG`
the gateways will only cache this information:

```
{  
   "data":"CAE=",
   "links":[  
      {  
         "Name":"arapp.json",
         "Size":1444,
         "Cid":{  
            "/":"QmQyxqZYccnbyc5EjWwZfu7ubLjCAUu7C3mPofSSrrGiWj"
         }
      },
      {  
         "Name":"artifact.json",
         "Size":13489,
         "Cid":{  
            "/":"QmcS2d4g56a89tXvideFJPrdG5vmj21b9S7mnuZYryrhwv"
         }
      },
      {  
         "Name":"build",
         "Size":9300968,
         "Cid":{  
            "/":"QmPa813qz45nodV7UeLePugmzmpAjGRJYH8iTNxECnVyVM"
         }
      },
      {  
         "Name":"code.sol",
         "Size":47210,
         "Cid":{  
            "/":"QmNRr6WMzBgYqGG4SPAwSi3441SQ2pNR2NBRQj3EQsLGC6"
         }
      },
      {  
         "Name":"contracts",
         "Size":21543,
         "Cid":{  
            "/":"QmY35Whth8gP1rw5QmMptQ8AkmYuvGdQ7pQw2dmgWFz3Wi"
         }
      },
      {  
         "Name":"manifest.json",
         "Size":181,
         "Cid":{  
            "/":"QmezXyk6Eb4uGGxNTrkeP74NAAR3kXW8FB5m2kQfFeFtTR"
         }
      },
      {  
         "Name":"migrations",
         "Size":202,
         "Cid":{  
            "/":"QmfXSbh4fA3SM9y54eRGBKHYgUrMFouBrVu2UPftznYZNE"
         }
      },
      {  
         "Name":"package-lock.json",
         "Size":637684,
         "Cid":{  
            "/":"Qmc8kkVT5bPn8HPzfdh94HeyFkrKAndLJoBUwHKGoivoMv"
         }
      },
      {  
         "Name":"package.json",
         "Size":2208,
         "Cid":{  
            "/":"QmRtpzJiBatid1Gzp2d6omj7Ytvk2ZUU3uoB4ZvGevVsSo"
         }
      },
      {  
         "Name":"scripts",
         "Size":212,
         "Cid":{  
            "/":"QmRkqrzJCMtYsgUYWQzmg2SKXCXKKcGXYgZivoNJkBHBTd"
         }
      },
      {  
         "Name":"test",
         "Size":23006,
         "Cid":{  
            "/":"QmRtCxfwpnqZNdWT6Y5KPfjbSsqNB4DAnyHtgGHJWC98Xm"
         }
      },
      {  
         "Name":"truffle.js",
         "Size":62,
         "Cid":{  
            "/":"QmfAYy5GYk6snCVHM1w3yDUnhqX8rK28gsnSfACE9cWZRr"
         }
      }
   ]
}
```
From https://ipfs.eth.aragon.network/api/v0/dag/get?arg=QmT2c6ffZ5e9vbQiQdWyRjZAxY9cMmZYNBEDW4Ne4dm2RG


What do you guys think about a command that queries all files recursively?
E.g.: `aragon ipfs propagate <hash>`

1. This would fetch the dag of the hash and check if it's a directory: https://github.com/Siderus/Orion/blob/release/0.9.1/app/api.js#L376
2. Query a bunch of gateways for each link and for links that are directories (`build`, `contracts`, etc.) recursively check the dag and query those as well.
3. Warn the user that gateways most likely have garbage collection enabled (which has a default interval of 1 hour, see https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#datastore)


Further improvements:
- we could run this command automatically on publish
- since we can't rely on gateways to cache these files indefinitely we could have a place where users request us to pin certain apps from `open.aragonpm.eth` to `ipfs.eth.aragon.network`, e.g. Nest apps (a rocket chat channel, a PR in `deployments`, etc)

**Comment by sohkai** [comment]
> There's a tricky part here. If you query a hash that is a directory, you only propagate the DAG of this hash, not the "children" files.

This part of the FAQ is definitely relying on some "tricks" with propagation; gateways default to loading the `index.html` and that includes the script and other assets used by the app so querying the gateway is usually good for everything directly used by the app. The additional requests for the `manifest.json` and `artifact.json` are in response to the problem you've noted :).

------------

> `aragon ipfs propagate <hash>`

This sounds amazing; can we please have this in the CLI? 😄 

------------

> since we can't rely on gateways to cache these files indefinitely we could have a place where users request us to pin certain apps from `open.aragonpm.eth` to `ipfs.eth.aragon.network`, e.g. Nest apps (a rocket chat channel, a PR in `deployments`, etc)

I wouldn't publicly advertise this, especially not after each publish in the CLI, since ideally users would be able to take care of this themselves. Probably just a link to a guide on how to properly make these files available?

**Comment by kernelwhisperer** [comment]
> I wouldn't publicly advertise this, especially not after each publish in the CLI, since ideally users would be able to take care of this themselves. Probably just a link to a guide on how to properly make these files available?

Oh, yeah, that makes sense. Perhaps just a warning suggesting the user to use this new command.

> This part of the FAQ is definitely relying on some "tricks" with propagation; gateways default to loading the `index.html`

Oh ok, good to know.

**Comment by izqui** [comment]
I think this is a great idea, if you ran this in a loop every 15-30 minutes to all known gateways would that mean you'd never be garbage collected? 😏

But about the pinning I don't think that the public IPFS node that Aragon manages should be free for all to use, as it would be abused at some point for sure.

If we built HTTP authorization support (you just need to initialize the ipfs api class with an extra option) and allowed people to target nodes they control or have access to port 5001, it would be  killer feature!

**Pull request merged**
