### PR TITLE
renaming

### PR DESCRIPTION
**Pull request by Smokyish**
Renaming of products.

No changes to file names and links.

### CODE REVIEW

**Comment by sohkai** [comment]
Ahh... would've been great to do this after https://github.com/aragon/hack/pull/56 was merged 😅

**Comment by cjyabraham** [comment]
Would you like any help with this @Smokyish.  I'm happy to finish it off.  Or would you like to do it?

**Comment by Smokyish** [comment]
@cjyabraham Yes please, happy to get help on this! :)

**Comment by cjyabraham** [comment]
Because there were so many conflicts due to the aragonOS 4 docs, I just [did the renaming again](https://github.com/aragon/hack/pull/62) from a fresh branch off of master.  If you're ok with that this PR can be closed.

**Comment by sohkai** [comment]
Closing for #62.

**Pull request closed without merging**
