### PR TITLE
Added some troubleshooting tips for IPFS propagation

### PR DESCRIPTION
**Pull request by stellarmagnet**

### CODE REVIEW

**Review by sohkai — APPROVED** [review]
:heart:

I usually manually request `artifact.json` and `manifest.json` in addition to the root hash, since they're not automatically loaded by the `index.html`. Might be good to add that as sub-steps of 3.

**Comment by stellarmagnet** [comment]
For me to learn: how do those additional requests relate to the gateway
automatically loading the index.html?
ᐧ
ᐧ

**Comment by sohkai** [comment]
If the app is packaged using a build processor like webpack or parcel, the index.html will automatically request any asset that the app needs. However, the `artifact.json` and `manifest.json` are usually not required by the app itself (only by the Aragon client) so they need to be requested separately.

IPFS gateways usually load the `index.html` if it's present at the root directory of a hash, so I usually ping:

- `<gateway>/ipfs/<hash>`
- `<gateway>/ipfs/<hash>/artifact.json`
- `<gateway>/ipfs/<hash>/manifest.json`

If either the `artifact.json` or `manifest.json` are missing, then the Aragon client won't be able to load the app irrespective of whether the app's assets are available or not.

**Comment by sohkai** [comment]
@stellarmagnet Edited the section a bit and made the bullets indented another level to show up better on our current theme.

**Pull request merged**
