### PR TITLE
Restyling of docs texts and titles

### PR DESCRIPTION
**Pull request by delfipolito**

### CODE REVIEW

**Review by 0xGabi — APPROVED** [review]
This looks much better with the changes!

**Comment by 0xGabi** [comment]
Also, I have a couple of style suggestion:
1. I notice bullet points have no space from margin. I think the style for bullet points in  [this page](https://docusaurus.io/docs/en/site-preparation) is more clear.
2. I review other projects using Docusaurus and I like the [side bar on this one](https://facebook.github.io/react-native/docs/getting-started). They use a scroll option for the sidebar.  

@delfi what you think? We can discuss about them and open a new PR if make sense.

**Comment by delfipolito** [comment]
Good catch on the bullet points @0xGabi !  I added the same margin as the paragraphs 👍. 
As for the sidebar, is a good option! We can discuss it with Adri and open another PR if its necessary :)

**Review by sohkai — APPROVED** [review]
✅ The sections are so much more clear now!

**Pull request merged**
