### PR TITLE
'Using the Aragon CLI' guide

### PR DESCRIPTION
**Pull request by izqui**

### CODE REVIEW

**Review by luisivan — CHANGES_REQUESTED** [review]
Where including commands, can you set the quote type as shell? That will do some syntax highlighting

**Comment by luisivan** [comment]
Actually, I just figured out `console` is fine, since `shell` doesn't change anything at all. Merging this

**Review by luisivan — APPROVED** [review]

**Comment by sohkai** [comment]
Usually it's `sh` or `bash` or etc rather than `shell`.

**Comment by luisivan** [comment]
Tried with `bash` too but I think the highlighting just doesn't do anything on it

**Comment by izqui** [comment]
Using `sh` and `bash` both result in very weird highlighting.

**Pull request merged**
