### PR TITLE
Update images in github-guide.md + minor edits

### LINKED ISSUE #160: GitHub guide for contributors
How to contribute with documentation.

---
This issue is funded with **150 DAI**, see more issues on our dao [projects app](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8).

**Funded**: [Mainnet Tx](https://etherscan.io/tx/0xcc9ec2062b8a17400144908bd99211de3f25bfe03c4bc3371697b52403834b6b)

### PR DESCRIPTION
**Pull request by unixpi**
closes #160 

Todo

- [x] Minor edits (tone + grammar)
- [x] Standardize image sizes and improve quality

### CODE REVIEW

**Comment by hackingclimate** [comment]
Ready for review

**Comment by unixpi** [comment]
@0xGabi ready for review

**Comment by 0xGabi** [comment]
@hackingclimate Great work! 🎉

Before I merge the new changes can you help me experiment with using Autark's projects app so I can assign you a bounty for you work done. 

I have create an issue #160 and I also attached a bounty to it on the [meshteam rinkeby dao](https://rinkeby.aragon.org/#/meshteam.aragonid.eth/0x2b2290c2370cbc59e7c77bd36072f801d5e996c8). Go ahead and sign-in with your GitHub account and request to work on that issue so I can approve it. The idea is that after you receive rinkeby DAI I'll manually make the mainnet transfer. If you have question reach me on Aragon chat. 

Also looking forward to make this workflow as easy as possible for new contributor...maybe a documentation we can work together next 😏

**Comment by unixpi** [comment]
> Before I merge the new changes can you help me experiment with using Autark's projects app so I can assign you a bounty for you work done.

Awesome. I've requested the assignment. This is really cool :)

> Also looking forward to make this workflow as easy as possible for new contributor...maybe a documentation we can work together next 😏

Great idea ❤️

**Comment by sohkai** [comment]
@hackingclimate It would also be great to update the CONTRIBUTING.md file to link to this getting started doc for new contributors :).

It may also make sense to move the `docs-internal` assets to be within `docs-internal`, as the `docs` hold the actual documentation site's assets.

**Comment by unixpi** [comment]
@sohkai good call :) updated here
https://github.com/aragon/hack/pull/162

**Pull request merged**
